version: "3.8"

services:
    ngnix:
        depends_on:
            - gooutsafe
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            default:
                aliases:
                    - user_api
                    - restaurants_api
                    - sendemail_api
        restart: on-failure
    gooutsafe:
        depends_on:
            - user_api
            - sendemail_api
            - restaurants_api
            - restaurants_api_2
        build: ./gateway
        volumes:
            - ./gateway/db:/code/monolith/db
            - ./gateway:/code
        ports:
            - 80:5000
        restart: on-failure
    user_api:
        build: ./users_microservice
        volumes:
            - ./users_microservice:/code
        restart: on-failure
    restaurants_api:
        build: ./restaurants_microservice
        volumes:
            - ./restaurants_microservice:/code
        restart: on-failure
    restaurants_api_2:
        depends_on:
            - restaurants_api
        build: ./restaurants_microservice
        volumes:
            - ./restaurants_microservice:/code
        restart: on-failure
    booking_api:
        build: ./booking_microservice
        volumes:
            - ./booking_microservice:/code
        restart: on-failure
    sendemail_api:
        build: ./email_microservice
        restart: on-failure
    celery:
        depends_on:
            - redis
        build: ./restaurants_microservice
        command: celery -A background.celery_app worker --loglevel=DEBUG -B
        links:
            -  redis
        volumes:
            - ./restaurants_microservice:/code/
        restart: on-failure
    celery_send_email:
        depends_on:
            - redis_email
        build: ./email_microservice
        command: celery -A background.celery_app worker --loglevel=DEBUG
        links:
            - redis
        restart: on-failure
    redis:
        image: "redis:alpine"
        container_name: rd01
        expose:
            - "6379"
        restart: on-failure
    redis_email:
        image: "redis:alpine"
        container_name: rd02
        command: --port 6380
        restart: on-failure
