version: "3.8"

services:
    ngnix:
        image: nginx:latest
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
    gooutsafe:
        depends_on:
            - user_api
            - sendemail_api
            - restaurants_api
        restart: always
        build: ./gateway
        volumes:
            - ./gateway/db:/code/monolith/db
            - ./gateway:/code
        ports:
            - 80:5000
    user_api:
        restart: always
        build: ./users_microservice
        volumes:
            - ./users_microservice:/code
    restaurants_api:
        restart: always
        build: ./restaurants_microservice
        volumes:
            - ./restaurants_microservice:/code
    sendemail_api:
        restart: always
        build: ./email_microservice
    celery:
        depends_on:
            - redis
        build: ./restaurants_microservice
        restart: always
        command: celery -A background.celery_app worker --loglevel=DEBUG -B
        links:
            -  redis
        volumes:
            - ./restaurants_microservice:/code/
    celery_send_email:
        depends_on:
            - redis_email
        build: ./email_microservice
        restart: always
        command: celery -A background.celery_app worker --loglevel=DEBUG
        links:
            - redis
    redis:
        image: "redis:alpine"
        container_name: rd01
        expose:
            - "6379"
    redis_email:
        image: "redis:alpine"
        container_name: rd02
        command: --port 6380
