version: "3.8"

services:
    ngnix:
        image: nginx:latest
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
          - "80:80"
    gooutsafe:
        depends_on:
            - redis
        restart: always
        build: ./gateway
        volumes:
            - ./gateway/db:/code/gateway/db
    user_api:
        restart: always
        build: ./users_microservice
    celery:
        depends_on:
            - redis
            - gooutsafe
        build: ./gateway
        restart: always
        command: celery -A gateway:celery worker --loglevel=DEBUG -B
        links:
            -  redis
        volumes:
            - ./gateway/db:/code/gateway/db
    redis:
        image: "redis:alpine"
        container_name: rd01
        expose:
            - "6379"
