version: "3.8"

services:
    ngnix:
        image: nginx:latest
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
          - "80:80"
    gooutsafe:
        depends_on:
            - redis
        restart: always
        build: .
        volumes:
            - ./monolith/db:/code/monolith/db
    celery:
        depends_on:
            - redis
            - gooutsafe
        build: .
        restart: always
        command: celery -A monolith:celery worker --loglevel=DEBUG -B
        links:
            -  redis
        volumes:
            - ./monolith/db:/code/monolith/db
    redis:
        image: "redis:alpine"
        container_name: rd01
        expose:
            - "6379"
