version: "3.8"

services:
    ngnix:
        image: nginx:latest
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
    gooutsafe:
        depends_on:
            - redis
        restart: always
        build: ./gateway
        volumes:
            - ./gateway/db:/code/monolith/db
            - ./gateway:/code
        ports:
            - 80:5000
    user_api:
        restart: always
        build: ./users_microservice
        volumes:
            - ./users_microservice:/code
    celery:
        depends_on:
            - redis
            - gooutsafe
        build: ./gateway
        restart: always
        command: celery -A monolith:celery worker --loglevel=DEBUG -B
        links:
            -  redis
        volumes:
            - ./gateway/db:/code/gateway/db
    redis:
        image: "redis:alpine"
        container_name: rd01
        expose:
            - "6379"
